<?php
use Migrations\AbstractSeed;

/**
 * Acos seed.
 */
class AcosSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'parent_id' => NULL,
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'controllers',
                'lft' => '1',
                'rght' => '192',
            ],
            [
                'id' => '2',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Bills',
                'lft' => '2',
                'rght' => '13',
            ],
            [
                'id' => '3',
                'parent_id' => '2',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '3',
                'rght' => '4',
            ],
            [
                'id' => '4',
                'parent_id' => '2',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '5',
                'rght' => '6',
            ],
            [
                'id' => '5',
                'parent_id' => '2',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '7',
                'rght' => '8',
            ],
            [
                'id' => '6',
                'parent_id' => '2',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '9',
                'rght' => '10',
            ],
            [
                'id' => '7',
                'parent_id' => '2',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '11',
                'rght' => '12',
            ],
            [
                'id' => '8',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Centres',
                'lft' => '14',
                'rght' => '25',
            ],
            [
                'id' => '9',
                'parent_id' => '8',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '15',
                'rght' => '16',
            ],
            [
                'id' => '10',
                'parent_id' => '8',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '17',
                'rght' => '18',
            ],
            [
                'id' => '11',
                'parent_id' => '8',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '19',
                'rght' => '20',
            ],
            [
                'id' => '12',
                'parent_id' => '8',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '21',
                'rght' => '22',
            ],
            [
                'id' => '13',
                'parent_id' => '8',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '23',
                'rght' => '24',
            ],
            [
                'id' => '14',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'CollectionCategories',
                'lft' => '26',
                'rght' => '37',
            ],
            [
                'id' => '15',
                'parent_id' => '14',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '27',
                'rght' => '28',
            ],
            [
                'id' => '16',
                'parent_id' => '14',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '29',
                'rght' => '30',
            ],
            [
                'id' => '17',
                'parent_id' => '14',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '31',
                'rght' => '32',
            ],
            [
                'id' => '18',
                'parent_id' => '14',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '33',
                'rght' => '34',
            ],
            [
                'id' => '19',
                'parent_id' => '14',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '35',
                'rght' => '36',
            ],
            [
                'id' => '20',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Collections',
                'lft' => '38',
                'rght' => '49',
            ],
            [
                'id' => '21',
                'parent_id' => '20',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '39',
                'rght' => '40',
            ],
            [
                'id' => '22',
                'parent_id' => '20',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '41',
                'rght' => '42',
            ],
            [
                'id' => '23',
                'parent_id' => '20',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '43',
                'rght' => '44',
            ],
            [
                'id' => '24',
                'parent_id' => '20',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '45',
                'rght' => '46',
            ],
            [
                'id' => '25',
                'parent_id' => '20',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '47',
                'rght' => '48',
            ],
            [
                'id' => '26',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Disabilities',
                'lft' => '50',
                'rght' => '61',
            ],
            [
                'id' => '27',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '51',
                'rght' => '52',
            ],
            [
                'id' => '28',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '53',
                'rght' => '54',
            ],
            [
                'id' => '29',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '55',
                'rght' => '56',
            ],
            [
                'id' => '30',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '57',
                'rght' => '58',
            ],
            [
                'id' => '31',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '59',
                'rght' => '60',
            ],
            [
                'id' => '32',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'DisqualifiedCandidates',
                'lft' => '62',
                'rght' => '73',
            ],
            [
                'id' => '33',
                'parent_id' => '32',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '63',
                'rght' => '64',
            ],
            [
                'id' => '34',
                'parent_id' => '32',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '65',
                'rght' => '66',
            ],
            [
                'id' => '35',
                'parent_id' => '32',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '67',
                'rght' => '68',
            ],
            [
                'id' => '36',
                'parent_id' => '32',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '69',
                'rght' => '70',
            ],
            [
                'id' => '37',
                'parent_id' => '32',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '71',
                'rght' => '72',
            ],
            [
                'id' => '38',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Districts',
                'lft' => '74',
                'rght' => '85',
            ],
            [
                'id' => '39',
                'parent_id' => '38',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '75',
                'rght' => '76',
            ],
            [
                'id' => '40',
                'parent_id' => '38',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '77',
                'rght' => '78',
            ],
            [
                'id' => '41',
                'parent_id' => '38',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '79',
                'rght' => '80',
            ],
            [
                'id' => '42',
                'parent_id' => '38',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '81',
                'rght' => '82',
            ],
            [
                'id' => '43',
                'parent_id' => '38',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '83',
                'rght' => '84',
            ],
            [
                'id' => '44',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Error',
                'lft' => '86',
                'rght' => '87',
            ],
            [
                'id' => '45',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'ExamTypes',
                'lft' => '88',
                'rght' => '99',
            ],
            [
                'id' => '46',
                'parent_id' => '45',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '89',
                'rght' => '90',
            ],
            [
                'id' => '47',
                'parent_id' => '45',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '91',
                'rght' => '92',
            ],
            [
                'id' => '48',
                'parent_id' => '45',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '93',
                'rght' => '94',
            ],
            [
                'id' => '49',
                'parent_id' => '45',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '95',
                'rght' => '96',
            ],
            [
                'id' => '50',
                'parent_id' => '45',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '97',
                'rght' => '98',
            ],
            [
                'id' => '51',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Groups',
                'lft' => '100',
                'rght' => '111',
            ],
            [
                'id' => '52',
                'parent_id' => '51',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '101',
                'rght' => '102',
            ],
            [
                'id' => '53',
                'parent_id' => '51',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '103',
                'rght' => '104',
            ],
            [
                'id' => '54',
                'parent_id' => '51',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '105',
                'rght' => '106',
            ],
            [
                'id' => '55',
                'parent_id' => '51',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '107',
                'rght' => '108',
            ],
            [
                'id' => '56',
                'parent_id' => '51',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '109',
                'rght' => '110',
            ],
            [
                'id' => '57',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Pages',
                'lft' => '112',
                'rght' => '115',
            ],
            [
                'id' => '58',
                'parent_id' => '57',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'display',
                'lft' => '113',
                'rght' => '114',
            ],
            [
                'id' => '59',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Regions',
                'lft' => '116',
                'rght' => '127',
            ],
            [
                'id' => '60',
                'parent_id' => '59',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '117',
                'rght' => '118',
            ],
            [
                'id' => '61',
                'parent_id' => '59',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '119',
                'rght' => '120',
            ],
            [
                'id' => '62',
                'parent_id' => '59',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '121',
                'rght' => '122',
            ],
            [
                'id' => '63',
                'parent_id' => '59',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '123',
                'rght' => '124',
            ],
            [
                'id' => '64',
                'parent_id' => '59',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '125',
                'rght' => '126',
            ],
            [
                'id' => '65',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Subjects',
                'lft' => '128',
                'rght' => '139',
            ],
            [
                'id' => '66',
                'parent_id' => '65',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '129',
                'rght' => '130',
            ],
            [
                'id' => '67',
                'parent_id' => '65',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '131',
                'rght' => '132',
            ],
            [
                'id' => '68',
                'parent_id' => '65',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '133',
                'rght' => '134',
            ],
            [
                'id' => '69',
                'parent_id' => '65',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '135',
                'rght' => '136',
            ],
            [
                'id' => '70',
                'parent_id' => '65',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '137',
                'rght' => '138',
            ],
            [
                'id' => '71',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Users',
                'lft' => '140',
                'rght' => '155',
            ],
            [
                'id' => '72',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '141',
                'rght' => '142',
            ],
            [
                'id' => '73',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '143',
                'rght' => '144',
            ],
            [
                'id' => '74',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '145',
                'rght' => '146',
            ],
            [
                'id' => '75',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '147',
                'rght' => '148',
            ],
            [
                'id' => '76',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '149',
                'rght' => '150',
            ],
            [
                'id' => '77',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'login',
                'lft' => '151',
                'rght' => '152',
            ],
            [
                'id' => '78',
                'parent_id' => '71',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'logout',
                'lft' => '153',
                'rght' => '154',
            ],
            [
                'id' => '79',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Acl',
                'lft' => '156',
                'rght' => '157',
            ],
            [
                'id' => '80',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'AdminLTE',
                'lft' => '158',
                'rght' => '159',
            ],
            [
                'id' => '81',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Bake',
                'lft' => '160',
                'rght' => '161',
            ],
            [
                'id' => '82',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'DebugKit',
                'lft' => '162',
                'rght' => '189',
            ],
            [
                'id' => '83',
                'parent_id' => '82',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Composer',
                'lft' => '163',
                'rght' => '166',
            ],
            [
                'id' => '84',
                'parent_id' => '83',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'checkDependencies',
                'lft' => '164',
                'rght' => '165',
            ],
            [
                'id' => '85',
                'parent_id' => '82',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'MailPreview',
                'lft' => '167',
                'rght' => '174',
            ],
            [
                'id' => '86',
                'parent_id' => '85',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '168',
                'rght' => '169',
            ],
            [
                'id' => '87',
                'parent_id' => '85',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'sent',
                'lft' => '170',
                'rght' => '171',
            ],
            [
                'id' => '88',
                'parent_id' => '85',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'email',
                'lft' => '172',
                'rght' => '173',
            ],
            [
                'id' => '89',
                'parent_id' => '82',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Panels',
                'lft' => '175',
                'rght' => '180',
            ],
            [
                'id' => '90',
                'parent_id' => '89',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '176',
                'rght' => '177',
            ],
            [
                'id' => '91',
                'parent_id' => '89',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '178',
                'rght' => '179',
            ],
            [
                'id' => '92',
                'parent_id' => '82',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Requests',
                'lft' => '181',
                'rght' => '184',
            ],
            [
                'id' => '93',
                'parent_id' => '92',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '182',
                'rght' => '183',
            ],
            [
                'id' => '94',
                'parent_id' => '82',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Toolbar',
                'lft' => '185',
                'rght' => '188',
            ],
            [
                'id' => '95',
                'parent_id' => '94',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'clearCache',
                'lft' => '186',
                'rght' => '187',
            ],
            [
                'id' => '96',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Migrations',
                'lft' => '190',
                'rght' => '191',
            ],
        ];

        $table = $this->table('acos');
        $table->insert($data)->save();
    }
}
