<?php
use Migrations\AbstractSeed;

/**
 * Districts seed.
 */
class DistrictsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'number' => '1',
                'name' => 'ARUSHA (V)',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '2',
                'number' => '2',
                'name' => 'ARUSHA (M)',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '3',
                'number' => '3',
                'name' => 'KARATU',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '4',
                'number' => '4',
                'name' => 'LONGIDO',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '5',
                'number' => '5',
                'name' => 'MERU',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '6',
                'number' => '6',
                'name' => 'MONDULI',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '7',
                'number' => '7',
                'name' => 'NGORONGORO',
                'detail' => '',
                'region_id' => '1',
            ],
            [
                'id' => '8',
                'number' => '1',
                'name' => 'ILALA',
                'detail' => '',
                'region_id' => '2',
            ],
            [
                'id' => '9',
                'number' => '2',
                'name' => 'KINONDONI',
                'detail' => '',
                'region_id' => '2',
            ],
            [
                'id' => '10',
                'number' => '3',
                'name' => 'TEMEKE',
                'detail' => '',
                'region_id' => '2',
            ],
            [
                'id' => '11',
                'number' => '4',
                'name' => 'UBUNGO',
                'detail' => '',
                'region_id' => '2',
            ],
            [
                'id' => '12',
                'number' => '5',
                'name' => 'KIGAMBONI',
                'detail' => '',
                'region_id' => '2',
            ],
            [
                'id' => '13',
                'number' => '1',
                'name' => 'BAHI',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '14',
                'number' => '2',
                'name' => 'DODOMA (M)',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '15',
                'number' => '3',
                'name' => 'KONDOA (V)',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '16',
                'number' => '4',
                'name' => 'MPWAPWA',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '17',
                'number' => '5',
                'name' => 'KONGWA',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '18',
                'number' => '6',
                'name' => 'CHAMWINO',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '19',
                'number' => '7',
                'name' => 'CHEMBA',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '20',
                'number' => '8',
                'name' => 'KONDOA (M)',
                'detail' => '',
                'region_id' => '3',
            ],
            [
                'id' => '21',
                'number' => '1',
                'name' => 'IRINGA (M)',
                'detail' => '',
                'region_id' => '4',
            ],
            [
                'id' => '22',
                'number' => '2',
                'name' => 'IRINGA (V)',
                'detail' => '',
                'region_id' => '4',
            ],
            [
                'id' => '23',
                'number' => '3',
                'name' => 'KILOLO',
                'detail' => '',
                'region_id' => '4',
            ],
            [
                'id' => '24',
                'number' => '4',
                'name' => 'MUFINDI',
                'detail' => '',
                'region_id' => '4',
            ],
            [
                'id' => '25',
                'number' => '5',
                'name' => 'MAFINGA (M)',
                'detail' => '',
                'region_id' => '4',
            ],
            [
                'id' => '26',
                'number' => '1',
                'name' => 'BIHARAMULO',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '27',
                'number' => '2',
                'name' => 'BUKOBA (V)',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '28',
                'number' => '3',
                'name' => 'BUKOBA (M)',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '29',
                'number' => '4',
                'name' => 'KARAGWE',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '30',
                'number' => '5',
                'name' => 'MULEBA',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '31',
                'number' => '6',
                'name' => 'NGARA',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '32',
                'number' => '7',
                'name' => 'KYERWA',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '33',
                'number' => '8',
                'name' => 'MISSENYI',
                'detail' => '',
                'region_id' => '5',
            ],
            [
                'id' => '34',
                'number' => '1',
                'name' => 'KASULU (V)',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '35',
                'number' => '2',
                'name' => 'KIBONDO',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '36',
                'number' => '3',
                'name' => 'KIGOMA (V)',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '37',
                'number' => '4',
                'name' => 'KIGOMA (M)',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '38',
                'number' => '5',
                'name' => 'BUHIGWE',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '39',
                'number' => '6',
                'name' => 'KAKONKO',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '40',
                'number' => '7',
                'name' => 'UVINZA',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '41',
                'number' => '8',
                'name' => 'KASULU (M)',
                'detail' => '',
                'region_id' => '6',
            ],
            [
                'id' => '42',
                'number' => '1',
                'name' => 'HAI',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '43',
                'number' => '2',
                'name' => 'MOSHI (V)',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '44',
                'number' => '3',
                'name' => 'MOSHI (M)',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '45',
                'number' => '4',
                'name' => 'MWANGA',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '46',
                'number' => '5',
                'name' => 'ROMBO',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '47',
                'number' => '6',
                'name' => 'SAME',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '48',
                'number' => '7',
                'name' => 'SIHA',
                'detail' => '',
                'region_id' => '7',
            ],
            [
                'id' => '49',
                'number' => '1',
                'name' => 'KILWA',
                'detail' => '',
                'region_id' => '8',
            ],
            [
                'id' => '50',
                'number' => '2',
                'name' => 'LINDI (V)',
                'detail' => '',
                'region_id' => '8',
            ],
            [
                'id' => '51',
                'number' => '3',
                'name' => 'LINDI (M)',
                'detail' => '',
                'region_id' => '8',
            ],
            [
                'id' => '52',
                'number' => '4',
                'name' => 'LIWALE',
                'detail' => '',
                'region_id' => '8',
            ],
            [
                'id' => '53',
                'number' => '5',
                'name' => 'NACHINGWEA',
                'detail' => '',
                'region_id' => '8',
            ],
            [
                'id' => '54',
                'number' => '6',
                'name' => 'RUANGWA',
                'detail' => '',
                'region_id' => '8',
            ],
            [
                'id' => '55',
                'number' => '1',
                'name' => 'BUNDA',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '56',
                'number' => '2',
                'name' => 'MUSOMA (V)',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '57',
                'number' => '3',
                'name' => 'MUSOMA (M)',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '58',
                'number' => '4',
                'name' => 'SERENGETI',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '59',
                'number' => '5',
                'name' => 'TARIME (V)',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '60',
                'number' => '6',
                'name' => 'RORYA',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '61',
                'number' => '7',
                'name' => 'BUTIAMA',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '62',
                'number' => '8',
                'name' => 'TARIME (M)',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '63',
                'number' => '9',
                'name' => 'BUNDA (M)',
                'detail' => '',
                'region_id' => '9',
            ],
            [
                'id' => '64',
                'number' => '1',
                'name' => 'CHUNYA',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '65',
                'number' => '2',
                'name' => 'BUSOKELO',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '66',
                'number' => '3',
                'name' => 'KYELA',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '67',
                'number' => '4',
                'name' => 'MBEYA (V)',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '68',
                'number' => '5',
                'name' => 'MBEYA (M)',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '69',
                'number' => '7',
                'name' => 'RUNGWE',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '70',
                'number' => '8',
                'name' => 'MBARALI',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '71',
                'number' => '9',
                'name' => 'BUSOKELO',
                'detail' => '',
                'region_id' => '10',
            ],
            [
                'id' => '72',
                'number' => '1',
                'name' => 'KILOMBERO',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '73',
                'number' => '2',
                'name' => 'KILOSA',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '74',
                'number' => '3',
                'name' => 'MOROGORO (V)',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '75',
                'number' => '4',
                'name' => 'MOROGORO (M)',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '76',
                'number' => '5',
                'name' => 'ULANGA',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '77',
                'number' => '6',
                'name' => 'MVOMERO',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '78',
                'number' => '7',
                'name' => 'GAIRO',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '79',
                'number' => '8',
                'name' => 'MALINYI',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '80',
                'number' => '9',
                'name' => 'IFAKARA (M)',
                'detail' => '',
                'region_id' => '11',
            ],
            [
                'id' => '81',
                'number' => '1',
                'name' => 'MASASI (M)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '82',
                'number' => '1',
                'name' => 'MASASI',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '83',
                'number' => '2',
                'name' => 'MTWARA (V)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '84',
                'number' => '3',
                'name' => 'MTWARA (M)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '85',
                'number' => '4',
                'name' => 'NANYUMBU',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '86',
                'number' => '4',
                'name' => 'NEWALA',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '87',
                'number' => '5',
                'name' => 'NEWALA (M)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '88',
                'number' => '5',
                'name' => 'TANDAHIMBA',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '89',
                'number' => '6',
                'name' => 'MASASI (M)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '90',
                'number' => '6',
                'name' => 'TANDAHIMBA (V)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '91',
                'number' => '7',
                'name' => 'NANYAMBA (M)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '92',
                'number' => '8',
                'name' => 'MASASI (V)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '93',
                'number' => '9',
                'name' => 'NEWALA (V)',
                'detail' => '',
                'region_id' => '12',
            ],
            [
                'id' => '94',
                'number' => '1',
                'name' => 'ILEMELA',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '95',
                'number' => '2',
                'name' => 'KWIMBA',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '96',
                'number' => '3',
                'name' => 'NYAMAGANA',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '97',
                'number' => '3',
                'name' => 'MAGU',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '98',
                'number' => '4',
                'name' => 'MWANZA JIJI',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '99',
                'number' => '5',
                'name' => 'MISUNGWI',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '100',
                'number' => '6',
                'name' => 'SENGEREMA',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '101',
                'number' => '7',
                'name' => 'UKEREWE',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '102',
                'number' => '8',
                'name' => 'BUCHOSA',
                'detail' => '',
                'region_id' => '13',
            ],
            [
                'id' => '103',
                'number' => '1',
                'name' => 'BAGAMOYO',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '104',
                'number' => '2',
                'name' => 'KIBAHA (V)',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '105',
                'number' => '3',
                'name' => 'KISARAWE',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '106',
                'number' => '4',
                'name' => 'MAFIA',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '107',
                'number' => '5',
                'name' => 'RUFIJI',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '108',
                'number' => '6',
                'name' => 'MKURANGA',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '109',
                'number' => '7',
                'name' => 'KIBAHA (M)',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '110',
                'number' => '8',
                'name' => 'CHALINZE',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '111',
                'number' => '9',
                'name' => 'KIBITI',
                'detail' => '',
                'region_id' => '14',
            ],
            [
                'id' => '112',
                'number' => '1',
                'name' => 'KALAMBO',
                'detail' => '',
                'region_id' => '15',
            ],
            [
                'id' => '113',
                'number' => '2',
                'name' => 'NKASI',
                'detail' => '',
                'region_id' => '15',
            ],
            [
                'id' => '114',
                'number' => '3',
                'name' => 'SUMBAWANGA (V)',
                'detail' => '',
                'region_id' => '15',
            ],
            [
                'id' => '115',
                'number' => '4',
                'name' => 'SUMBAWANGA (M)',
                'detail' => '',
                'region_id' => '15',
            ],
            [
                'id' => '116',
                'number' => '1',
                'name' => 'MBINGA(V)',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '117',
                'number' => '2',
                'name' => 'TUNDURU',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '118',
                'number' => '3',
                'name' => 'SONGEA (V)',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '119',
                'number' => '4',
                'name' => 'SONGEA (M)',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '120',
                'number' => '5',
                'name' => 'NAMTUMBO',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '121',
                'number' => '6',
                'name' => 'NYASA',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '122',
                'number' => '7',
                'name' => 'MBINGA (M)',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '123',
                'number' => '8',
                'name' => 'MADABA',
                'detail' => '',
                'region_id' => '16',
            ],
            [
                'id' => '124',
                'number' => '1',
                'name' => 'KAHAMA (M)',
                'detail' => '',
                'region_id' => '17',
            ],
            [
                'id' => '125',
                'number' => '2',
                'name' => 'KISHAPU',
                'detail' => '',
                'region_id' => '17',
            ],
            [
                'id' => '126',
                'number' => '3',
                'name' => 'MSALALA',
                'detail' => '',
                'region_id' => '17',
            ],
            [
                'id' => '127',
                'number' => '4',
                'name' => 'SHINYANGA (M)',
                'detail' => '',
                'region_id' => '17',
            ],
            [
                'id' => '128',
                'number' => '5',
                'name' => 'SHINYANGA (V)',
                'detail' => '',
                'region_id' => '17',
            ],
            [
                'id' => '129',
                'number' => '6',
                'name' => 'USHETU',
                'detail' => '',
                'region_id' => '17',
            ],
            [
                'id' => '130',
                'number' => '1',
                'name' => 'IRAMBA',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '131',
                'number' => '2',
                'name' => 'MANYONI',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '132',
                'number' => '3',
                'name' => 'SINGIDA (V)',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '133',
                'number' => '4',
                'name' => 'SINGIDA (M)',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '134',
                'number' => '5',
                'name' => 'IKUNGI',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '135',
                'number' => '6',
                'name' => 'MKALAMA',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '136',
                'number' => '7',
                'name' => 'ITIGI',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '137',
                'number' => '8',
                'name' => 'KINAMPANDA',
                'detail' => '',
                'region_id' => '18',
            ],
            [
                'id' => '138',
                'number' => '1',
                'name' => 'IGUNGA',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '139',
                'number' => '2',
                'name' => 'NZEGA',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '140',
                'number' => '3',
                'name' => 'TABORA (M)',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '141',
                'number' => '5',
                'name' => 'URAMBO',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '142',
                'number' => '6',
                'name' => 'SIKONGE',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '143',
                'number' => '7',
                'name' => 'KALIUA',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '144',
                'number' => '8',
                'name' => 'NZEGA (M)',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '145',
                'number' => '9',
                'name' => 'UYUI',
                'detail' => '',
                'region_id' => '19',
            ],
            [
                'id' => '146',
                'number' => '1',
                'name' => 'HANDENI',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '147',
                'number' => '2',
                'name' => 'KOROGWE (V)',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '148',
                'number' => '3',
                'name' => 'LUSHOTO',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '149',
                'number' => '4',
                'name' => 'MUHEZA',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '150',
                'number' => '5',
                'name' => 'PANGANI',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '151',
                'number' => '7',
                'name' => 'TANGA (M)',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '152',
                'number' => '8',
                'name' => 'KILINDI',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '153',
                'number' => '9',
                'name' => 'KOROGWE (M)',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '154',
                'number' => '10',
                'name' => 'MKINGA',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '155',
                'number' => '11',
                'name' => 'BUMBULI',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '156',
                'number' => '12',
                'name' => 'HANDENI (M)',
                'detail' => '',
                'region_id' => '20',
            ],
            [
                'id' => '157',
                'number' => '1',
                'name' => 'BABATI (V)',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '158',
                'number' => '2',
                'name' => 'HANANG',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '159',
                'number' => '3',
                'name' => 'KITETO',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '160',
                'number' => '4',
                'name' => 'MBULU',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '161',
                'number' => '5',
                'name' => 'SIMANJIRO',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '162',
                'number' => '6',
                'name' => 'BABATI (M)',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '163',
                'number' => '7',
                'name' => 'MBULU (M)',
                'detail' => '',
                'region_id' => '21',
            ],
            [
                'id' => '164',
                'number' => '1',
                'name' => 'MAGHARIBI B',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '165',
                'number' => '1',
                'name' => 'MJINI',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '166',
                'number' => '2',
                'name' => 'KASKAZINI B',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '167',
                'number' => '3',
                'name' => 'MAGHARIBI A',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '168',
                'number' => '4',
                'name' => 'MAGHARIBI A',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '169',
                'number' => '4',
                'name' => 'MJINI',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '170',
                'number' => '5',
                'name' => 'MJINI',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '171',
                'number' => '7',
                'name' => 'MAGHARIBI B',
                'detail' => '',
                'region_id' => '22',
            ],
            [
                'id' => '172',
                'number' => '1',
                'name' => 'CHAKECHAKE',
                'detail' => '',
                'region_id' => '23',
            ],
            [
                'id' => '173',
                'number' => '2',
                'name' => 'MKOANI',
                'detail' => '',
                'region_id' => '23',
            ],
            [
                'id' => '174',
                'number' => '3',
                'name' => 'MKOANI',
                'detail' => '',
                'region_id' => '23',
            ],
            [
                'id' => '175',
                'number' => '1',
                'name' => 'BUKOMBE',
                'detail' => '',
                'region_id' => '24',
            ],
            [
                'id' => '176',
                'number' => '2',
                'name' => 'CHATO',
                'detail' => '',
                'region_id' => '24',
            ],
            [
                'id' => '177',
                'number' => '3',
                'name' => 'GEITA (M)',
                'detail' => '',
                'region_id' => '24',
            ],
            [
                'id' => '178',
                'number' => '4',
                'name' => 'GEITA (V)',
                'detail' => '',
                'region_id' => '24',
            ],
            [
                'id' => '179',
                'number' => '5',
                'name' => 'MBOGWE',
                'detail' => '',
                'region_id' => '24',
            ],
            [
                'id' => '180',
                'number' => '6',
                'name' => 'NYANG\'HWALE',
                'detail' => '',
                'region_id' => '24',
            ],
            [
                'id' => '181',
                'number' => '1',
                'name' => 'MLELE',
                'detail' => '',
                'region_id' => '25',
            ],
            [
                'id' => '182',
                'number' => '2',
                'name' => 'MPANDA (M)',
                'detail' => '',
                'region_id' => '25',
            ],
            [
                'id' => '183',
                'number' => '3',
                'name' => 'MPANDA (V)',
                'detail' => '',
                'region_id' => '25',
            ],
            [
                'id' => '184',
                'number' => '4',
                'name' => 'NSIMBO',
                'detail' => '',
                'region_id' => '25',
            ],
            [
                'id' => '185',
                'number' => '5',
                'name' => 'MPIMBWE',
                'detail' => '',
                'region_id' => '25',
            ],
            [
                'id' => '186',
                'number' => '1',
                'name' => 'LUDEWA',
                'detail' => '',
                'region_id' => '26',
            ],
            [
                'id' => '187',
                'number' => '2',
                'name' => 'MAKETE',
                'detail' => '',
                'region_id' => '26',
            ],
            [
                'id' => '188',
                'number' => '3',
                'name' => 'MAKAMBAKO (M)',
                'detail' => '',
                'region_id' => '26',
            ],
            [
                'id' => '189',
                'number' => '4',
                'name' => 'NJOMBE (M)',
                'detail' => '',
                'region_id' => '26',
            ],
            [
                'id' => '190',
                'number' => '5',
                'name' => 'NJOMBE (V)',
                'detail' => '',
                'region_id' => '26',
            ],
            [
                'id' => '191',
                'number' => '6',
                'name' => 'WANGING\'OMBE',
                'detail' => '',
                'region_id' => '26',
            ],
            [
                'id' => '192',
                'number' => '1',
                'name' => 'BARIADI (M)',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '193',
                'number' => '2',
                'name' => 'BARIADI (V)',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '194',
                'number' => '3',
                'name' => 'BUSEGA',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '195',
                'number' => '4',
                'name' => 'ITILIMA',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '196',
                'number' => '4',
                'name' => 'MWADUI',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '197',
                'number' => '5',
                'name' => 'MASWA',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '198',
                'number' => '6',
                'name' => 'MEATU',
                'detail' => '',
                'region_id' => '27',
            ],
            [
                'id' => '199',
                'number' => '1',
                'name' => 'KASKAZINI A',
                'detail' => '',
                'region_id' => '28',
            ],
            [
                'id' => '200',
                'number' => '2',
                'name' => 'KASKAZINI B',
                'detail' => '',
                'region_id' => '28',
            ],
            [
                'id' => '201',
                'number' => '3',
                'name' => 'KUSINI',
                'detail' => '',
                'region_id' => '29',
            ],
            [
                'id' => '202',
                'number' => '6',
                'name' => 'KATI',
                'detail' => '',
                'region_id' => '29',
            ],
            [
                'id' => '203',
                'number' => '1',
                'name' => 'MICHEWENI',
                'detail' => '',
                'region_id' => '30',
            ],
            [
                'id' => '204',
                'number' => '2',
                'name' => 'WETE',
                'detail' => '',
                'region_id' => '30',
            ],
            [
                'id' => '205',
                'number' => '1',
                'name' => 'SONGWE',
                'detail' => '',
                'region_id' => '31',
            ],
            [
                'id' => '206',
                'number' => '2',
                'name' => 'ILEJE',
                'detail' => '',
                'region_id' => '31',
            ],
            [
                'id' => '207',
                'number' => '3',
                'name' => 'MBOZI',
                'detail' => '',
                'region_id' => '31',
            ],
            [
                'id' => '208',
                'number' => '4',
                'name' => 'MOMBA',
                'detail' => '',
                'region_id' => '31',
            ],
            [
                'id' => '209',
                'number' => '5',
                'name' => 'TUNDUMA (M)',
                'detail' => '',
                'region_id' => '31',
            ],
        ];

        $table = $this->table('districts');
        $table->insert($data)->save();
    }
}
