<?php
use Migrations\AbstractSeed;

/**
 * Subjects seed.
 */
class SubjectsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'code' => '11',
                'name' => 'CIVICS',
                'short_name' => 'CIV',
                'exam_type_id' => '1',
            ],
            [
                'id' => '2',
                'code' => '12',
                'name' => 'HISTORY',
                'short_name' => 'HIST',
                'exam_type_id' => '1',
            ],
            [
                'id' => '3',
                'code' => '13',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEO',
                'exam_type_id' => '1',
            ],
            [
                'id' => '4',
                'code' => '14',
                'name' => 'BIBLE KNOWLEDGE',
                'short_name' => 'B/KNOWL',
                'exam_type_id' => '1',
            ],
            [
                'id' => '5',
                'code' => '15',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'E/D/KIISLAMU',
                'exam_type_id' => '1',
            ],
            [
                'id' => '6',
                'code' => '16',
                'name' => 'FINE ART',
                'short_name' => 'F.ART',
                'exam_type_id' => '1',
            ],
            [
                'id' => '7',
                'code' => '17',
                'name' => 'MUSIC',
                'short_name' => 'MUSIC',
                'exam_type_id' => '1',
            ],
            [
                'id' => '8',
                'code' => '18',
                'name' => 'PHYSICAL EDUCATION',
                'short_name' => 'PHY EDU',
                'exam_type_id' => '1',
            ],
            [
                'id' => '9',
                'code' => '21',
                'name' => 'KISWAHILI',
                'short_name' => 'KISW',
                'exam_type_id' => '1',
            ],
            [
                'id' => '10',
                'code' => '22',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGL',
                'exam_type_id' => '1',
            ],
            [
                'id' => '11',
                'code' => '23',
                'name' => 'FRENCH LANGUAGE ',
                'short_name' => 'FREN',
                'exam_type_id' => '1',
            ],
            [
                'id' => '12',
                'code' => '24',
                'name' => 'LITERATURE IN ENGLISH',
                'short_name' => 'LIT ENG',
                'exam_type_id' => '1',
            ],
            [
                'id' => '13',
                'code' => '25',
                'name' => 'ARABIC LANGUAGE',
                'short_name' => 'ARABIC LANGUAGE',
                'exam_type_id' => '1',
            ],
            [
                'id' => '14',
                'code' => '31',
                'name' => 'PHYSICS',
                'short_name' => 'PHY',
                'exam_type_id' => '1',
            ],
            [
                'id' => '15',
                'code' => '32',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEM',
                'exam_type_id' => '1',
            ],
            [
                'id' => '16',
                'code' => '33',
                'name' => 'BIOLOGY',
                'short_name' => 'BIO',
                'exam_type_id' => '1',
            ],
            [
                'id' => '17',
                'code' => '34',
                'name' => 'AGRICULTURAL SCIENCE',
                'short_name' => 'AGRI',
                'exam_type_id' => '1',
            ],
            [
                'id' => '18',
                'code' => '35',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENG SC',
                'exam_type_id' => '1',
            ],
            [
                'id' => '19',
                'code' => '36',
                'name' => 'INFORMATION & COMPUTER STUDIES',
                'short_name' => 'COMP STUD',
                'exam_type_id' => '1',
            ],
            [
                'id' => '20',
                'code' => '41',
                'name' => 'BASIC MATHEMATICS',
                'short_name' => 'B/MATH',
                'exam_type_id' => '1',
            ],
            [
                'id' => '21',
                'code' => '42',
                'name' => 'ADDITIONAL MATHEMATICS',
                'short_name' => 'ADD MATH',
                'exam_type_id' => '1',
            ],
            [
                'id' => '22',
                'code' => '51',
                'name' => 'FOOD & NUTRITION',
                'short_name' => 'FOOD',
                'exam_type_id' => '1',
            ],
            [
                'id' => '23',
                'code' => '52',
                'name' => 'TEXTILE & DRESSMAKING',
                'short_name' => 'TEXTILE',
                'exam_type_id' => '1',
            ],
            [
                'id' => '24',
                'code' => '61',
                'name' => 'COMMERCE',
                'short_name' => 'COMM',
                'exam_type_id' => '1',
            ],
            [
                'id' => '25',
                'code' => '62',
                'name' => 'BOOK-KEEPING',
                'short_name' => 'B/KEEPING',
                'exam_type_id' => '1',
            ],
            [
                'id' => '26',
                'code' => '63',
                'name' => 'TYPEWRITING',
                'short_name' => 'TYPEWRITING',
                'exam_type_id' => '1',
            ],
            [
                'id' => '27',
                'code' => '71',
                'name' => 'BUILDING CONSTRUCTION',
                'short_name' => 'BLD CONSTR',
                'exam_type_id' => '1',
            ],
            [
                'id' => '28',
                'code' => '72',
                'name' => 'ARCHTECTURAL DRAUGHTING',
                'short_name' => 'ARCH DRAUGHT',
                'exam_type_id' => '1',
            ],
            [
                'id' => '29',
                'code' => '73',
                'name' => 'SURVEYING',
                'short_name' => 'SURVEYING',
                'exam_type_id' => '1',
            ],
            [
                'id' => '30',
                'code' => '74',
                'name' => 'CARPENTRY & JOINERY',
                'short_name' => 'CARP & JOIN',
                'exam_type_id' => '1',
            ],
            [
                'id' => '31',
                'code' => '75',
                'name' => 'BRICKWORK & MASONRY',
                'short_name' => 'BRI & MAS',
                'exam_type_id' => '1',
            ],
            [
                'id' => '32',
                'code' => '76',
                'name' => 'PAINTING & SIGN WRITING',
                'short_name' => 'PAINT & SIGN',
                'exam_type_id' => '1',
            ],
            [
                'id' => '33',
                'code' => '77',
                'name' => 'PLUMBING',
                'short_name' => 'PLUMBING',
                'exam_type_id' => '1',
            ],
            [
                'id' => '34',
                'code' => '81',
                'name' => 'ELECTRICAL INSTALLATION',
                'short_name' => 'ELECT INST',
                'exam_type_id' => '1',
            ],
            [
                'id' => '35',
                'code' => '82',
                'name' => 'ELECTRICAL ENGINEERING SCIENCE',
                'short_name' => 'ELECT ENG SC',
                'exam_type_id' => '1',
            ],
            [
                'id' => '36',
                'code' => '83',
                'name' => 'RADIO & TV SERVICING',
                'short_name' => 'RADIO & TV',
                'exam_type_id' => '1',
            ],
            [
                'id' => '37',
                'code' => '84',
                'name' => 'ELECTRICAL DRAUGHTING',
                'short_name' => 'ELECT DRAUGHT',
                'exam_type_id' => '1',
            ],
            [
                'id' => '38',
                'code' => '85',
                'name' => 'REFRIGERATION & AIR CONDITION',
                'short_name' => 'REFRIG & AIR COND',
                'exam_type_id' => '1',
            ],
            [
                'id' => '39',
                'code' => '92',
                'name' => 'WORKSHOP TECHNOLOGY',
                'short_name' => 'W/SHOP TECH',
                'exam_type_id' => '1',
            ],
            [
                'id' => '40',
                'code' => '93',
                'name' => 'MOTOR VEHICLE MECHANICS',
                'short_name' => 'MOT VEH MECH',
                'exam_type_id' => '1',
            ],
            [
                'id' => '41',
                'code' => '94',
                'name' => 'WELDING & METAL FABRICATION',
                'short_name' => 'WELD & MET ',
                'exam_type_id' => '1',
            ],
            [
                'id' => '42',
                'code' => '95',
                'name' => 'FITTING & TURNING',
                'short_name' => 'FITT & TURN',
                'exam_type_id' => '1',
            ],
            [
                'id' => '43',
                'code' => '96',
                'name' => 'AUTO ELECTRICS',
                'short_name' => 'AUTO ELECT',
                'exam_type_id' => '1',
            ],
            [
                'id' => '44',
                'code' => '97',
                'name' => 'MECHANICAL DRAUGHTING',
                'short_name' => 'MECH DRAUGHT',
                'exam_type_id' => '1',
            ],
            [
                'id' => '45',
                'code' => '86',
                'name' => 'PLANT & EQUIPMENT MAINTANANCE',
                'short_name' => 'PL & EQUIP MAINT',
                'exam_type_id' => '1',
            ],
            [
                'id' => '46',
                'code' => '91',
                'name' => 'TECHINICAL DRAWING',
                'short_name' => 'TECH DRAWING',
                'exam_type_id' => '1',
            ],
            [
                'id' => '47',
                'code' => '10',
                'name' => 'QUALIFYING TEST',
                'short_name' => 'QUALIFYING TEST',
                'exam_type_id' => '4',
            ],
            [
                'id' => '48',
                'code' => '111',
                'name' => 'GENERAL STUDIES',
                'short_name' => 'G/STUDIES',
                'exam_type_id' => '2',
            ],
            [
                'id' => '49',
                'code' => '112',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'exam_type_id' => '2',
            ],
            [
                'id' => '50',
                'code' => '113',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGR',
                'exam_type_id' => '2',
            ],
            [
                'id' => '51',
                'code' => '114',
                'name' => 'DIVINITY',
                'short_name' => 'DIVINITY',
                'exam_type_id' => '2',
            ],
            [
                'id' => '52',
                'code' => '115',
                'name' => 'ISLAMIC KNOWLEDGE',
                'short_name' => 'IS/KNOWLEDGE',
                'exam_type_id' => '2',
            ],
            [
                'id' => '53',
                'code' => '121',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'exam_type_id' => '2',
            ],
            [
                'id' => '54',
                'code' => '122',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH',
                'exam_type_id' => '2',
            ],
            [
                'id' => '55',
                'code' => '123',
                'name' => 'FRENCH',
                'short_name' => 'FRENCH',
                'exam_type_id' => '2',
            ],
            [
                'id' => '56',
                'code' => '125',
                'name' => 'ARABIC',
                'short_name' => 'ARABIC',
                'exam_type_id' => '2',
            ],
            [
                'id' => '57',
                'code' => '131',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'exam_type_id' => '2',
            ],
            [
                'id' => '58',
                'code' => '132',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'exam_type_id' => '2',
            ],
            [
                'id' => '59',
                'code' => '133',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'exam_type_id' => '2',
            ],
            [
                'id' => '60',
                'code' => '134',
                'name' => 'SCIENCE AND PRACTICE OF AGRICULTURE',
                'short_name' => 'AGRICULTURE',
                'exam_type_id' => '2',
            ],
            [
                'id' => '61',
                'code' => '136',
                'name' => 'COMPUTER SCIENCE',
                'short_name' => 'COMP/SCIENCE',
                'exam_type_id' => '2',
            ],
            [
                'id' => '62',
                'code' => '141',
                'name' => 'BASIC APPLIED MATHEMATICS',
                'short_name' => 'BAM',
                'exam_type_id' => '2',
            ],
            [
                'id' => '63',
                'code' => '142',
                'name' => 'ADVANCED MATHEMATICS',
                'short_name' => 'ADV/MATHS',
                'exam_type_id' => '2',
            ],
            [
                'id' => '64',
                'code' => '151',
                'name' => 'ECONOMICS',
                'short_name' => 'ECONOMICS',
                'exam_type_id' => '2',
            ],
            [
                'id' => '65',
                'code' => '152',
                'name' => 'COMMERCE',
                'short_name' => 'COMMERCE',
                'exam_type_id' => '2',
            ],
            [
                'id' => '66',
                'code' => '153',
                'name' => 'ACCOUNTANCY',
                'short_name' => 'ACCOUNTANCY',
                'exam_type_id' => '2',
            ],
            [
                'id' => '67',
                'code' => '155',
                'name' => 'FOOD & NUTRITION',
                'short_name' => 'F & NUTRITION',
                'exam_type_id' => '2',
            ],
            [
                'id' => '68',
                'code' => '98',
                'name' => 'FOUNDRY & BLACKSMITH',
                'short_name' => 'FOUNDRY & BLACKSMITH',
                'exam_type_id' => '1',
            ],
            [
                'id' => '69',
                'code' => '611',
                'name' => 'URAIA',
                'short_name' => 'URAIA',
                'exam_type_id' => '4',
            ],
            [
                'id' => '70',
                'code' => '612',
                'name' => 'MBINU - MAARIFA YA JAMII',
                'short_name' => 'MBINU / MAARIFA YA JAMII',
                'exam_type_id' => '4',
            ],
            [
                'id' => '71',
                'code' => '613',
                'name' => 'SOCIAL STUDIES TEACH. METHODS',
                'short_name' => 'SOCIAL STUDIES TEACH. METHODS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '72',
                'code' => '615',
                'name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'short_name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'exam_type_id' => '4',
            ],
            [
                'id' => '73',
                'code' => '621',
                'name' => 'MBINU ZA KUFUNDISHIA KISWAHILI',
                'short_name' => 'MBINU / KUFUNDISHIA KISWAHILI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '74',
                'code' => '622',
                'name' => 'ENGLISH LANG. TEACHING METHODS',
                'short_name' => 'ENGLISH LANG. TEACHING METHODS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '75',
                'code' => '630',
                'name' => 'MBINU ZA KUFUNDISHIA SAYANSI',
                'short_name' => 'MBINU ZA KUFUNDISHIA SAYANSI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '76',
                'code' => '631',
                'name' => 'SCIENCE TEACHING METHODS',
                'short_name' => 'SCIENCE TEACHING METHODS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '77',
                'code' => '636',
                'name' => 'SCIENCE',
                'short_name' => 'SCIENCE',
                'exam_type_id' => '4',
            ],
            [
                'id' => '78',
                'code' => '640',
                'name' => 'MBINU ZA KUFUNDISHIA HISABATI',
                'short_name' => 'MBINU ZA KUFUNDISHIA HISABATI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '79',
                'code' => '641',
                'name' => 'MATHEMATICS TEACHING METHODS',
                'short_name' => 'MATHEMATICS TEACHING METHODS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '80',
                'code' => '642',
                'name' => 'SAYANSI KIMU VITENDO',
                'short_name' => 'SAYANSI KIMU VITENDO',
                'exam_type_id' => '4',
            ],
            [
                'id' => '81',
                'code' => '643',
                'name' => 'SAYANSI KIMU USHONAJI NGUO NA MAVAZI',
                'short_name' => 'SAYANSI KIMU USHONAJI/MAVAZI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '82',
                'code' => '644',
                'name' => 'SAYANSI KIMU UDOBI',
                'short_name' => 'SAYANSI KIMU UDOBI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '83',
                'code' => '645',
                'name' => 'SAYANSI KIMU ELIMU YA NYUMBA',
                'short_name' => 'SAYANSI KIMU ELIMU NYUMBANI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '84',
                'code' => '646',
                'name' => 'SAYANSI KIMU UPISHI NA LISHE',
                'short_name' => 'SAYANSI KIMU UPISHI NA LISHE',
                'exam_type_id' => '4',
            ],
            [
                'id' => '85',
                'code' => '647',
                'name' => 'SAYANSI KIMU UENDESHAJI MIRADI',
                'short_name' => 'SAYANSI KIMU UENDESHAJI MIRADI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '86',
                'code' => '648',
                'name' => 'SAYANSI UPIMAJI NA TATHMINI',
                'short_name' => 'SAYANSI UPIMAJI NA TATHMINI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '87',
                'code' => '649',
                'name' => 'SAYANSI KIMU UFUNDISHAJI',
                'short_name' => 'SAYANSI KIMU UFUNDISHAJI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '88',
                'code' => '650',
                'name' => 'UFUNDI',
                'short_name' => 'UFUNDI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '89',
                'code' => '652',
                'name' => 'VOCATIONAL SKILLS TCH. METHODS',
                'short_name' => 'VOCATIONAL SKILLS TCH. METHODS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '90',
                'code' => '653',
                'name' => 'EARLY CHILD.CARE EDUC.TCH.MTHD',
                'short_name' => 'EARLY CHILD.CARE EDUC.TCH.MTHD',
                'exam_type_id' => '4',
            ],
            [
                'id' => '91',
                'code' => '654',
                'name' => 'EARLY CHILDHOOD CARE EDUCATION',
                'short_name' => 'EARLY CHILDHOOD CARE EDUCATION',
                'exam_type_id' => '4',
            ],
            [
                'id' => '92',
                'code' => '655',
                'name' => 'EDUC.PSYCHOLOGY GUID.&COUNSELL',
                'short_name' => 'EDUC.PSYCHOLOGY GUID.&COUNSELL',
                'exam_type_id' => '4',
            ],
            [
                'id' => '93',
                'code' => '656',
                'name' => 'EDUC.RESEARCH MEASUREMENT-EVAL',
                'short_name' => 'EDUC.RESEARCH MEASUREMENT-EVAL',
                'exam_type_id' => '4',
            ],
            [
                'id' => '94',
                'code' => '657',
                'name' => 'FOUNDATIONS OF EDUCATION',
                'short_name' => 'FOUNDATIONS OF EDUCATION',
                'exam_type_id' => '4',
            ],
            [
                'id' => '95',
                'code' => '651',
                'name' => 'MBINU / STADI ZA KAZI',
                'short_name' => 'MBINU / STADI ZA KAZI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '96',
                'code' => '658',
                'name' => 'CURRICULUM AND TEACHING',
                'short_name' => 'CURRICULUM AND TEACHING',
                'exam_type_id' => '4',
            ],
            [
                'id' => '97',
                'code' => '659',
                'name' => 'MBINU / MALEZI ELIMU YA AWALI',
                'short_name' => 'MBINU / MALEZI ELIMU YA AWALI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '98',
                'code' => '660',
                'name' => 'MALEZI YA ELIMU YA AWALI',
                'short_name' => 'MALEZI YA ELIMU YA AWALI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '99',
                'code' => '661',
                'name' => 'SAIKOLOJIA YA ELIMU & KUNASIHI',
                'short_name' => 'SAIKOLOJIA / ELIMU & KUNASIHI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '100',
                'code' => '662',
                'name' => 'UTAFITI WA KIEL. UPIM. & TATHMINI',
                'short_name' => 'UTAFITI/KIEL. UPIM. & TATHMINI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '101',
                'code' => '663',
                'name' => 'MISINGI YA ELIMU',
                'short_name' => 'MISINGI YA ELIMU',
                'exam_type_id' => '4',
            ],
            [
                'id' => '102',
                'code' => '664',
                'name' => 'MITAALA NA UFUNDISHAJI',
                'short_name' => 'MITAALA NA UFUNDISHAJI',
                'exam_type_id' => '4',
            ],
            [
                'id' => '103',
                'code' => '665',
                'name' => 'GENERAL COURSE: S.N.E PAPER',
                'short_name' => 'GENERAL COURSE/S.N.E PAPER',
                'exam_type_id' => '4',
            ],
            [
                'id' => '104',
                'code' => '666',
                'name' => 'V.I: BRAILLE SKILLS',
                'short_name' => 'V.I.BRAILLE SKILLS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '105',
                'code' => '667',
                'name' => 'V.I: ORIENTATION & MOBILITY TRN',
                'short_name' => 'V.I.ORIENTATION & MOBILITY TRN',
                'exam_type_id' => '4',
            ],
            [
                'id' => '106',
                'code' => '668',
                'name' => 'V.I: METHODOLOGY',
                'short_name' => 'V.I.METHODOLOGY',
                'exam_type_id' => '4',
            ],
            [
                'id' => '107',
                'code' => '669',
                'name' => 'V.I: PHYSICAL EDUCATION',
                'short_name' => 'V.I.PHYSICAL EDUCATION',
                'exam_type_id' => '4',
            ],
            [
                'id' => '108',
                'code' => '670',
                'name' => 'V.I: VISUAL IMP/DEAF BLINDNESS',
                'short_name' => 'VISUAL IMP/DEAF BLINDNESS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '109',
                'code' => '671',
                'name' => 'H.I: PSYCHOLOGY',
                'short_name' => 'H.I. PSYCHOLOGY',
                'exam_type_id' => '4',
            ],
            [
                'id' => '110',
                'code' => '672',
                'name' => 'H.I: AUDIOLOGY',
                'short_name' => 'H.I. AUDIOLOGY',
                'exam_type_id' => '4',
            ],
            [
                'id' => '111',
                'code' => '673',
                'name' => 'H.I: METHODOLOGY',
                'short_name' => 'H.I. METHODOLOGY',
                'exam_type_id' => '4',
            ],
            [
                'id' => '112',
                'code' => '674',
                'name' => 'H.I: PHYISICAL EDUCATION',
                'short_name' => 'H.I. PHYISICAL EDUCATION',
                'exam_type_id' => '4',
            ],
            [
                'id' => '113',
                'code' => '675',
                'name' => 'H.I: COMMUNICATION',
                'short_name' => 'H.I. COMMUNICATION',
                'exam_type_id' => '4',
            ],
            [
                'id' => '114',
                'code' => '676',
                'name' => 'I.I: PSYCHOLOGY',
                'short_name' => 'I.I. PSYCHOLOGY',
                'exam_type_id' => '4',
            ],
            [
                'id' => '115',
                'code' => '677',
                'name' => 'I.I: COMMUNICAT. & MANAGEMENT',
                'short_name' => 'I.I. COMMUNICAT. & MANAGEMENT',
                'exam_type_id' => '4',
            ],
            [
                'id' => '116',
                'code' => '678',
                'name' => 'I.I: METHODOLOGY',
                'short_name' => 'I.I. METHODOLOGY',
                'exam_type_id' => '4',
            ],
            [
                'id' => '117',
                'code' => '679',
                'name' => 'I.I: PHYSICAL EDUCATION',
                'short_name' => 'I.I. PHYSICAL EDUCATION',
                'exam_type_id' => '4',
            ],
            [
                'id' => '118',
                'code' => '610',
                'name' => 'CIVICS',
                'short_name' => 'CIVICS',
                'exam_type_id' => '4',
            ],
            [
                'id' => '119',
                'code' => '611',
                'name' => 'URAIA',
                'short_name' => 'URAIA',
                'exam_type_id' => '5',
            ],
            [
                'id' => '120',
                'code' => '612',
                'name' => 'MBINU / MAARIFA YA JAMII',
                'short_name' => 'MBINU / MAARIFA YA JAMII',
                'exam_type_id' => '5',
            ],
            [
                'id' => '121',
                'code' => '613',
                'name' => 'SOCIAL STUDIES TEACH. METHODS',
                'short_name' => 'SOCIAL STUDIES TEACH. METHODS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '122',
                'code' => '615',
                'name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'short_name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'exam_type_id' => '5',
            ],
            [
                'id' => '123',
                'code' => '621',
                'name' => 'MBINU / KUFUNDISHIA KISWAHILI',
                'short_name' => 'MBINU / KUFUNDISHIA KISWAHILI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '124',
                'code' => '622',
                'name' => 'ENGLISH LANG. TEACHING METHODS',
                'short_name' => 'ENGLISH LANG. TEACHING METHODS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '125',
                'code' => '630',
                'name' => 'MBINU ZA KUFUNDISHIA SAYANSI',
                'short_name' => 'MBINU ZA KUFUNDISHIA SAYANSI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '126',
                'code' => '631',
                'name' => 'SCIENCE TEACHING METHODS',
                'short_name' => 'SCIENCE TEACHING METHODS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '127',
                'code' => '636',
                'name' => 'SCIENCE',
                'short_name' => 'SCIENCE',
                'exam_type_id' => '5',
            ],
            [
                'id' => '128',
                'code' => '640',
                'name' => 'MBINU ZA KUFUNDISHIA HISABATI',
                'short_name' => 'MBINU ZA KUFUNDISHIA HISABATI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '129',
                'code' => '641',
                'name' => 'MATHEMATICS TEACHING METHODS',
                'short_name' => 'MATHEMATICS TEACHING METHODS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '130',
                'code' => '642',
                'name' => 'SAYANSI KIMU VITENDO',
                'short_name' => 'SAYANSI KIMU VITENDO',
                'exam_type_id' => '5',
            ],
            [
                'id' => '131',
                'code' => '643',
                'name' => 'SAYANSI KIMU USHONAJI NGUO NA MAVAZI',
                'short_name' => 'SAYANSI KIMU USHONAJI/MAVAZI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '132',
                'code' => '644',
                'name' => 'SAYANSI KIMU UDOBI',
                'short_name' => 'SAYANSI KIMU UDOBI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '133',
                'code' => '645',
                'name' => 'SAYANSI KIMU ELIMU YA NYUMBA',
                'short_name' => 'SAYANSI KIMU ELIMU NYUMBANI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '134',
                'code' => '646',
                'name' => 'SAYANSI KIMU UPISHI NA LISHE',
                'short_name' => 'SAYANSI KIMU UPISHI NA LISHE',
                'exam_type_id' => '5',
            ],
            [
                'id' => '135',
                'code' => '647',
                'name' => 'SAYANSI KIMU UENDESHAJI MIRADI',
                'short_name' => 'SAYANSI KIMU UENDESHAJI MIRADI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '136',
                'code' => '648',
                'name' => 'SAYANSI UPIMAJI NA TATHMINI',
                'short_name' => 'SAYANSI UPIMAJI NA TATHMINI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '137',
                'code' => '649',
                'name' => 'SAYANSI KIMU UFUNDISHAJI',
                'short_name' => 'SAYANSI KIMU UFUNDISHAJI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '138',
                'code' => '650',
                'name' => 'UFUNDI',
                'short_name' => 'UFUNDI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '139',
                'code' => '652',
                'name' => 'VOCATIONAL SKILLS TCH. METHODS',
                'short_name' => 'VOCATIONAL SKILLS TCH. METHODS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '140',
                'code' => '653',
                'name' => 'EARLY CHILD.CARE EDUC.TCH.MTHD',
                'short_name' => 'EARLY CHILD.CARE EDUC.TCH.MTHD',
                'exam_type_id' => '5',
            ],
            [
                'id' => '141',
                'code' => '654',
                'name' => 'EARLY CHILDHOOD CARE EDUCATION',
                'short_name' => 'EARLY CHILDHOOD CARE EDUCATION',
                'exam_type_id' => '5',
            ],
            [
                'id' => '142',
                'code' => '655',
                'name' => 'EDUC.PSYCHOLOGY GUID.&COUNSELL',
                'short_name' => 'EDUC.PSYCHOLOGY GUID.&COUNSELL',
                'exam_type_id' => '5',
            ],
            [
                'id' => '143',
                'code' => '656',
                'name' => 'EDUC.RESEARCH MEASUREMENT-EVAL',
                'short_name' => 'EDUC.RESEARCH MEASUREMENT-EVAL',
                'exam_type_id' => '5',
            ],
            [
                'id' => '144',
                'code' => '657',
                'name' => 'FOUNDATIONS OF EDUCATION',
                'short_name' => 'FOUNDATIONS OF EDUCATION',
                'exam_type_id' => '5',
            ],
            [
                'id' => '145',
                'code' => '651',
                'name' => 'MBINU / STADI ZA KAZI',
                'short_name' => 'MBINU / STADI ZA KAZI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '146',
                'code' => '658',
                'name' => 'CURRICULUM AND TEACHING',
                'short_name' => 'CURRICULUM AND TEACHING',
                'exam_type_id' => '5',
            ],
            [
                'id' => '147',
                'code' => '659',
                'name' => 'MBINU / MALEZI ELIMU YA AWALI',
                'short_name' => 'MBINU / MALEZI ELIMU YA AWALI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '148',
                'code' => '660',
                'name' => 'MALEZI YA ELIMU YA AWALI',
                'short_name' => 'MALEZI YA ELIMU YA AWALI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '149',
                'code' => '661',
                'name' => 'SAIKOLOJIA YA ELIMU & KUNASIHI',
                'short_name' => 'SAIKOLOJIA / ELIMU & KUNASIHI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '150',
                'code' => '662',
                'name' => 'UTAFITI WA KIEL. UPIM. & TATHMINI',
                'short_name' => 'UTAFITI/KIEL. UPIM. & TATHMINI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '151',
                'code' => '663',
                'name' => 'MISINGI YA ELIMU',
                'short_name' => 'MISINGI YA ELIMU',
                'exam_type_id' => '5',
            ],
            [
                'id' => '152',
                'code' => '664',
                'name' => 'MITAALA NA UFUNDISHAJI',
                'short_name' => 'MITAALA NA UFUNDISHAJI',
                'exam_type_id' => '5',
            ],
            [
                'id' => '153',
                'code' => '665',
                'name' => 'GENERAL COURSE: S.N.E PAPER',
                'short_name' => 'GENERAL COURSE/S.N.E PAPER',
                'exam_type_id' => '5',
            ],
            [
                'id' => '154',
                'code' => '666',
                'name' => 'V.I: BRAILLE SKILLS',
                'short_name' => 'V.I.BRAILLE SKILLS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '155',
                'code' => '667',
                'name' => 'V.I: ORIENTATION & MOBILITY TRN',
                'short_name' => 'V.I.ORIENTATION & MOBILITY TRN',
                'exam_type_id' => '5',
            ],
            [
                'id' => '156',
                'code' => '668',
                'name' => 'V.I: METHODOLOGY',
                'short_name' => 'V.I.METHODOLOGY',
                'exam_type_id' => '5',
            ],
            [
                'id' => '157',
                'code' => '669',
                'name' => 'V.I: PHYSICAL EDUCATION',
                'short_name' => 'V.I.PHYSICAL EDUCATION',
                'exam_type_id' => '5',
            ],
            [
                'id' => '158',
                'code' => '670',
                'name' => 'V.I: VISUAL IMP/DEAF BLINDNESS',
                'short_name' => 'VISUAL IMP/DEAF BLINDNESS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '159',
                'code' => '671',
                'name' => 'H.I: PSYCHOLOGY',
                'short_name' => 'H.I. PSYCHOLOGY',
                'exam_type_id' => '5',
            ],
            [
                'id' => '160',
                'code' => '672',
                'name' => 'H.I: AUDIOLOGY',
                'short_name' => 'H.I. AUDIOLOGY',
                'exam_type_id' => '5',
            ],
            [
                'id' => '161',
                'code' => '673',
                'name' => 'H.I: METHODOLOGY',
                'short_name' => 'H.I. METHODOLOGY',
                'exam_type_id' => '5',
            ],
            [
                'id' => '162',
                'code' => '674',
                'name' => 'H.I: PHYISICAL EDUCATION',
                'short_name' => 'H.I. PHYISICAL EDUCATION',
                'exam_type_id' => '5',
            ],
            [
                'id' => '163',
                'code' => '675',
                'name' => 'H.I: COMMUNICATION',
                'short_name' => 'H.I. COMMUNICATION',
                'exam_type_id' => '5',
            ],
            [
                'id' => '164',
                'code' => '676',
                'name' => 'I.I: PSYCHOLOGY',
                'short_name' => 'I.I. PSYCHOLOGY',
                'exam_type_id' => '5',
            ],
            [
                'id' => '165',
                'code' => '677',
                'name' => 'I.I: COMMUNICAT. & MANAGEMENT',
                'short_name' => 'I.I. COMMUNICAT. & MANAGEMENT',
                'exam_type_id' => '5',
            ],
            [
                'id' => '166',
                'code' => '678',
                'name' => 'I.I: METHODOLOGY',
                'short_name' => 'I.I. METHODOLOGY',
                'exam_type_id' => '5',
            ],
            [
                'id' => '167',
                'code' => '679',
                'name' => 'I.I: PHYSICAL EDUCATION',
                'short_name' => 'I.I. PHYSICAL EDUCATION',
                'exam_type_id' => '5',
            ],
            [
                'id' => '168',
                'code' => '610',
                'name' => 'CIVICS',
                'short_name' => 'CIVICS',
                'exam_type_id' => '5',
            ],
            [
                'id' => '169',
                'code' => '710',
                'name' => 'CIVICS PEDAGOGY',
                'short_name' => 'CIVICS PEDAGOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '170',
                'code' => '711',
                'name' => 'DEVELOPMENT STUDIES',
                'short_name' => 'DEVELOPMENT STUDIES',
                'exam_type_id' => '6',
            ],
            [
                'id' => '171',
                'code' => '712',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '172',
                'code' => '713',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGRAPHY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '173',
                'code' => '715',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'MBINU YA KUFUNDISHIA DINI YA KIISLAM',
                'exam_type_id' => '6',
            ],
            [
                'id' => '174',
                'code' => '716',
                'name' => 'FINE ART & CRAFT',
                'short_name' => 'FINE ART & CRAFT',
                'exam_type_id' => '6',
            ],
            [
                'id' => '175',
                'code' => '717',
                'name' => 'MUSIC',
                'short_name' => 'MUSIC 1',
                'exam_type_id' => '6',
            ],
            [
                'id' => '176',
                'code' => '718',
                'name' => 'MUSIC TEACHING METHODS',
                'short_name' => 'MUSIC TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '177',
                'code' => '719',
                'name' => 'THEATRE ARTS',
                'short_name' => 'THEATRE ARTS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '178',
                'code' => '720',
                'name' => 'THEATRE ARTS TEACHING METHODS',
                'short_name' => 'THEATRE ARTS TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '179',
                'code' => '721',
                'name' => 'LUGHA YA KISWAHILI',
                'short_name' => 'LUGHA YA KISWAHILI',
                'exam_type_id' => '6',
            ],
            [
                'id' => '180',
                'code' => '722',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'exam_type_id' => '6',
            ],
            [
                'id' => '181',
                'code' => '723',
                'name' => 'FRENCH LANGUAGE',
                'short_name' => 'FRENCH LANGUAGE',
                'exam_type_id' => '6',
            ],
            [
                'id' => '182',
                'code' => '724',
                'name' => 'COMMUNICATION SKILLS',
                'short_name' => 'COMMUNICATION SKILLS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '183',
                'code' => '725',
                'name' => 'MBINU ZA KUF. LUGHA YA KIARABU',
                'short_name' => 'MBINU ZA KUF. LUGHA YA KIARABU',
                'exam_type_id' => '6',
            ],
            [
                'id' => '184',
                'code' => '726',
                'name' => 'FINE ART & CRAFT TEACHING METHODS',
                'short_name' => 'FINE ART &CRAFTS TEACH METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '185',
                'code' => '727',
                'name' => 'PHYCL. EDUC. AND SPORT T/METHODS',
                'short_name' => 'PHYCL. EDUC. AND SPORT T/METHD',
                'exam_type_id' => '6',
            ],
            [
                'id' => '186',
                'code' => '731',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '187',
                'code' => '732',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '188',
                'code' => '733',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '189',
                'code' => '735',
                'name' => 'AGRICULTURE TEACHING METHODS',
                'short_name' => 'AGRICULTURE TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '190',
                'code' => '736',
                'name' => 'PHYSICAL EDUCATION & SPORT',
                'short_name' => 'PHYSICAL EDUCATION & SPORT',
                'exam_type_id' => '6',
            ],
            [
                'id' => '191',
                'code' => '738',
                'name' => 'INFORMATION & COMM. TECH. (ICT)',
                'short_name' => 'INFORMATION & COMM. TECH. (ICT)',
                'exam_type_id' => '6',
            ],
            [
                'id' => '192',
                'code' => '740',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '193',
                'code' => '741',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '194',
                'code' => '742',
                'name' => 'MATHEMATICS TEACHING METHODS',
                'short_name' => 'MATHEMATICS TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '195',
                'code' => '734',
                'name' => 'AGRICULTURE',
                'short_name' => 'AGRICULTURE',
                'exam_type_id' => '6',
            ],
            [
                'id' => '196',
                'code' => '743',
                'name' => 'CIVICS TEACHING METHODS',
                'short_name' => 'CIVICS TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '197',
                'code' => '744',
                'name' => 'GENERAL STUDIES',
                'short_name' => 'GENERAL STUDIES',
                'exam_type_id' => '6',
            ],
            [
                'id' => '198',
                'code' => '745',
                'name' => 'HISTORY TEACHING METHODS',
                'short_name' => 'HISTORY TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '199',
                'code' => '746',
                'name' => 'GEOGRAPHY TEACHING METHODS',
                'short_name' => 'GEOGRAPHY TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '200',
                'code' => '747',
                'name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'short_name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'exam_type_id' => '6',
            ],
            [
                'id' => '201',
                'code' => '748',
                'name' => 'MBINU ZA KUFUNDISHIA KISWAHILI',
                'short_name' => 'MBINU ZA KUFUNDISHIA KISWAHILI',
                'exam_type_id' => '6',
            ],
            [
                'id' => '202',
                'code' => '749',
                'name' => 'ENGLISH LANGUAGE TEACH.METHODS',
                'short_name' => 'ENGLISH LANGUAGE TEACH.METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '203',
                'code' => '750',
                'name' => 'EDUCATION MEDIA & TECHNOLOGY',
                'short_name' => 'EDUCATION MEDIA & TECHNOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '204',
                'code' => '751',
                'name' => 'COMMERCE TEACHING METHODS',
                'short_name' => 'COMMERCE TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '205',
                'code' => '752',
                'name' => 'BOOK-KEEPING TEACHING METHODS',
                'short_name' => 'BOOK-KEEPING TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '206',
                'code' => '753',
                'name' => 'HOME ECONOMICS',
                'short_name' => 'HOME ECONOMICS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '207',
                'code' => '754',
                'name' => 'COMMERCE',
                'short_name' => 'COMMERCE',
                'exam_type_id' => '6',
            ],
            [
                'id' => '208',
                'code' => '755',
                'name' => 'BOOK-KEEPING',
                'short_name' => 'BOOK-KEEPING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '209',
                'code' => '756',
                'name' => 'PHYSICS TEACHING METHODS',
                'short_name' => 'PHYSICS TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '210',
                'code' => '757',
                'name' => 'CHEMISTRY TEACHING METHODS',
                'short_name' => 'CHEMISTRY TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '211',
                'code' => '758',
                'name' => 'BIOLOGY TEACHING METHODS',
                'short_name' => 'BIOLOGY TEACHING METHODS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '212',
                'code' => '761',
                'name' => 'EDUC. PSYCH. GUIDNS & COUNSEL.',
                'short_name' => 'EDUC. PSYCH. GUIDNS & COUNSEL.',
                'exam_type_id' => '6',
            ],
            [
                'id' => '213',
                'code' => '762',
                'name' => 'EDUC. RES. MEAS. & EVALUATION',
                'short_name' => 'EDUC. RES. MEAS. & EVALUATION',
                'exam_type_id' => '6',
            ],
            [
                'id' => '214',
                'code' => '763',
                'name' => 'FOUNDATIONS OF EDUCATION',
                'short_name' => 'FOUNDATIONS OF EDUCATION',
                'exam_type_id' => '6',
            ],
            [
                'id' => '215',
                'code' => '764',
                'name' => 'CURRICULUM AND TEACHING',
                'short_name' => 'CURRICULUM AND TEACHING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '216',
                'code' => '766',
                'name' => 'V.I: BRAILLE SKILLS',
                'short_name' => 'VI:BRAILLE SKILLS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '217',
                'code' => '767',
                'name' => 'V.I: METHODOLOGY',
                'short_name' => 'VI:METHODOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '218',
                'code' => '768',
                'name' => 'V.I: VISUAL IMPAIRMENT',
                'short_name' => 'VI:VISUAL IMPAIRMENT',
                'exam_type_id' => '6',
            ],
            [
                'id' => '219',
                'code' => '769',
                'name' => 'V.I: ORIENTATION & MOBILITY',
                'short_name' => 'VI:ORIENTATION & MOBILITY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '220',
                'code' => '770',
                'name' => 'H.I: HABILITATION & REHABILITA.',
                'short_name' => 'HI:HABILITATION & REHABILITA.',
                'exam_type_id' => '6',
            ],
            [
                'id' => '221',
                'code' => '771',
                'name' => 'H.I: AUDIOLOGY',
                'short_name' => 'HI:AUDIOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '222',
                'code' => '772',
                'name' => 'EDUCATION',
                'short_name' => 'EDUCATION',
                'exam_type_id' => '6',
            ],
            [
                'id' => '223',
                'code' => '773',
                'name' => 'H.I: HEARING IMPAIRMENT AND THE EAR',
                'short_name' => 'HI:HEARING IMPAIRMENT/THE EAR',
                'exam_type_id' => '6',
            ],
            [
                'id' => '224',
                'code' => '774',
                'name' => 'H.I: METHODOLOGY',
                'short_name' => 'HI:METHODOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '225',
                'code' => '775',
                'name' => 'I.I: NEUROLOGY',
                'short_name' => 'II:NEUROLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '226',
                'code' => '776',
                'name' => 'I.I: S.E.G LEARNING DISABILITIES',
                'short_name' => 'II:S.E.G LEARNING DISABILITIES',
                'exam_type_id' => '6',
            ],
            [
                'id' => '227',
                'code' => '777',
                'name' => 'I.I: METHODOLOGY',
                'short_name' => 'II:METHODOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '228',
                'code' => '778',
                'name' => 'I.I: ASSESSMENT HABIL. & REHAB',
                'short_name' => 'II:ASSESSMENT HABIL. & REHAB',
                'exam_type_id' => '6',
            ],
            [
                'id' => '229',
                'code' => '779',
                'name' => 'I.I: SUPPORT SERVICES',
                'short_name' => 'I.I:SUPPORT SERVICES',
                'exam_type_id' => '6',
            ],
            [
                'id' => '230',
                'code' => '781',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENGINEERING SCIENCE',
                'exam_type_id' => '6',
            ],
            [
                'id' => '231',
                'code' => '782',
                'name' => 'ARCHITECTURAL DRAWING',
                'short_name' => 'ARCHITECTURAL DRAWING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '232',
                'code' => '783',
                'name' => 'BUILDING CONSTRUCTION',
                'short_name' => 'BUILDING CONSTRUCTION',
                'exam_type_id' => '6',
            ],
            [
                'id' => '233',
                'code' => '784',
                'name' => 'BRICKWORK & MASONRY',
                'short_name' => 'BRICKWORK & MASONRY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '234',
                'code' => '785',
                'name' => 'WOODWORK',
                'short_name' => 'WOODWORK',
                'exam_type_id' => '6',
            ],
            [
                'id' => '235',
                'code' => '786',
                'name' => 'PAINTING & SIGNWRITING',
                'short_name' => 'PAINTING & SIGNWRITING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '236',
                'code' => '787',
                'name' => 'PLUMBING & PIPEFITTING',
                'short_name' => 'PLUMBING & PIPEFITTING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '237',
                'code' => '788',
                'name' => 'TECHNICAL DRAWING',
                'short_name' => 'TECHNICAL DRAWING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '238',
                'code' => '789',
                'name' => 'METALWORK & MECH PRACT.',
                'short_name' => 'METALWORK & MECH PRACT.',
                'exam_type_id' => '6',
            ],
            [
                'id' => '239',
                'code' => '790',
                'name' => 'AUTOMOBILE TECHNOLOGY',
                'short_name' => 'AUTOMOBILE TECHNOLOGY',
                'exam_type_id' => '6',
            ],
            [
                'id' => '240',
                'code' => '791',
                'name' => 'MACHINE SHOP PRACTICE',
                'short_name' => 'MACHINE SHOP PRACTICE',
                'exam_type_id' => '6',
            ],
            [
                'id' => '241',
                'code' => '792',
                'name' => 'WELDING & FABRICATION',
                'short_name' => 'WELDING & FABRICATION',
                'exam_type_id' => '6',
            ],
            [
                'id' => '242',
                'code' => '793',
                'name' => 'ELECTRONICS',
                'short_name' => 'ELECTRONICS',
                'exam_type_id' => '6',
            ],
            [
                'id' => '243',
                'code' => '794',
                'name' => 'ELECTRICAL INSTALLATION',
                'short_name' => 'ELECTRICAL INSTALLATION',
                'exam_type_id' => '6',
            ],
            [
                'id' => '244',
                'code' => '795',
                'name' => 'ELECTRICAL DRAWING',
                'short_name' => 'ELECTRICAL DRAWING',
                'exam_type_id' => '6',
            ],
            [
                'id' => '245',
                'code' => '710',
                'name' => 'CIVICS PEDAGOGY',
                'short_name' => 'CIVICS PEDAGOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '246',
                'code' => '711',
                'name' => 'DEVELOPMENT STUDIES',
                'short_name' => 'DEVELOPMENT STUDIES',
                'exam_type_id' => '7',
            ],
            [
                'id' => '247',
                'code' => '712',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '248',
                'code' => '713',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGRAPHY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '249',
                'code' => '715',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'ELIMU YA DINI YA KIISLAMU',
                'exam_type_id' => '7',
            ],
            [
                'id' => '250',
                'code' => '716',
                'name' => 'FINE ART & CRAFT',
                'short_name' => 'FINE ART & CRAFT',
                'exam_type_id' => '7',
            ],
            [
                'id' => '251',
                'code' => '717',
                'name' => 'MUSIC 1',
                'short_name' => 'MUSIC 1',
                'exam_type_id' => '7',
            ],
            [
                'id' => '252',
                'code' => '718',
                'name' => 'MUSIC TEACHING METHODS',
                'short_name' => 'MUSIC TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '253',
                'code' => '719',
                'name' => 'THEATRE ARTS',
                'short_name' => 'THEATRE ARTS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '254',
                'code' => '720',
                'name' => 'THEATRE ARTS TEACHING METHODS',
                'short_name' => 'THEATRE ARTS TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '255',
                'code' => '721',
                'name' => 'LUGHA YA KISWAHILI',
                'short_name' => 'LUGHA YA KISWAHILI',
                'exam_type_id' => '7',
            ],
            [
                'id' => '256',
                'code' => '722',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'exam_type_id' => '7',
            ],
            [
                'id' => '257',
                'code' => '723',
                'name' => 'FRENCH LANGUAGE',
                'short_name' => 'FRENCH LANGUAGE',
                'exam_type_id' => '7',
            ],
            [
                'id' => '258',
                'code' => '724',
                'name' => 'COMMUNICATION SKILLS',
                'short_name' => 'COMMUNICATION SKILLS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '259',
                'code' => '725',
                'name' => 'MBINU ZA KUF. LUGHA YA KIARABU',
                'short_name' => 'MBINU ZA KUF. LUGHA YA KIARABU',
                'exam_type_id' => '7',
            ],
            [
                'id' => '260',
                'code' => '726',
                'name' => 'FINE ART &CRAFTS TEACH METHODS',
                'short_name' => 'FINE ART &CRAFTS TEACH METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '261',
                'code' => '727',
                'name' => 'PHYCL. EDUC. AND SPORT T/METHD',
                'short_name' => 'PHYCL. EDUC. AND SPORT T/METHD',
                'exam_type_id' => '7',
            ],
            [
                'id' => '262',
                'code' => '731',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '263',
                'code' => '732',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '264',
                'code' => '733',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '265',
                'code' => '735',
                'name' => 'AGRICULTURE TEACHING METHODS',
                'short_name' => 'AGRICULTURE TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '266',
                'code' => '736',
                'name' => 'PHYSICAL EDUCATION & SPORT',
                'short_name' => 'PHYSICAL EDUCATION & SPORT',
                'exam_type_id' => '7',
            ],
            [
                'id' => '267',
                'code' => '738',
                'name' => 'INFORMATION &COMM. TECH. (ICT)',
                'short_name' => 'INFORMATION &COMM. TECH. (ICT)',
                'exam_type_id' => '7',
            ],
            [
                'id' => '268',
                'code' => '740',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '269',
                'code' => '741',
                'name' => 'MATHEMATICS',
                'short_name' => 'MATHEMATICS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '270',
                'code' => '742',
                'name' => 'MATHEMATICS TEACHING METHODS',
                'short_name' => 'MATHEMATICS TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '271',
                'code' => '734',
                'name' => 'AGRICULTURE',
                'short_name' => 'AGRICULTURE',
                'exam_type_id' => '7',
            ],
            [
                'id' => '272',
                'code' => '743',
                'name' => 'CIVICS TEACHING METHODS',
                'short_name' => 'CIVICS TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '273',
                'code' => '744',
                'name' => 'GENERAL STUDIES',
                'short_name' => 'GENERAL STUDIES',
                'exam_type_id' => '7',
            ],
            [
                'id' => '274',
                'code' => '745',
                'name' => 'HISTORY TEACHING METHODS',
                'short_name' => 'HISTORY TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '275',
                'code' => '746',
                'name' => 'GEOGRAPHY TEACHING METHODS',
                'short_name' => 'GEOGRAPHY TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '276',
                'code' => '747',
                'name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'short_name' => 'MBINU ZA KUF.ELM.DINI KIISLAMU',
                'exam_type_id' => '7',
            ],
            [
                'id' => '277',
                'code' => '748',
                'name' => 'MBINU ZA KUFUNDISHIA KISWAHILI',
                'short_name' => 'MBINU ZA KUFUNDISHIA KISWAHILI',
                'exam_type_id' => '7',
            ],
            [
                'id' => '278',
                'code' => '749',
                'name' => 'ENGLISH LANGUAGE TEACH.METHODS',
                'short_name' => 'ENGLISH LANGUAGE TEACH.METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '279',
                'code' => '750',
                'name' => 'EDUCATION MEDIA & TECHNOLOGY',
                'short_name' => 'EDUCATION MEDIA & TECHNOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '280',
                'code' => '751',
                'name' => 'COMMERCE TEACHING METHODS',
                'short_name' => 'COMMERCE TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '281',
                'code' => '752',
                'name' => 'BOOK-KEEPING TEACHING METHODS',
                'short_name' => 'BOOK-KEEPING TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '282',
                'code' => '753',
                'name' => 'HOME ECONOMICS',
                'short_name' => 'HOME ECONOMICS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '283',
                'code' => '754',
                'name' => 'COMMERCE',
                'short_name' => 'COMMERCE',
                'exam_type_id' => '7',
            ],
            [
                'id' => '284',
                'code' => '755',
                'name' => 'BOOK-KEEPING',
                'short_name' => 'BOOK-KEEPING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '285',
                'code' => '756',
                'name' => 'PHYSICS TEACHING METHODS',
                'short_name' => 'PHYSICS TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '286',
                'code' => '757',
                'name' => 'CHEMISTRY TEACHING METHODS',
                'short_name' => 'CHEMISTRY TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '287',
                'code' => '758',
                'name' => 'BIOLOGY TEACHING METHODS',
                'short_name' => 'BIOLOGY TEACHING METHODS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '288',
                'code' => '761',
                'name' => 'EDUC. PSYCH. GUIDNS & COUNSEL.',
                'short_name' => 'EDUC. PSYCH. GUIDNS & COUNSEL.',
                'exam_type_id' => '7',
            ],
            [
                'id' => '289',
                'code' => '762',
                'name' => 'EDUC. RES. MEAS. & EVALUATION',
                'short_name' => 'EDUC. RES. MEAS. & EVALUATION',
                'exam_type_id' => '7',
            ],
            [
                'id' => '290',
                'code' => '763',
                'name' => 'FOUNDATIONS OF EDUCATION',
                'short_name' => 'FOUNDATIONS OF EDUCATION',
                'exam_type_id' => '7',
            ],
            [
                'id' => '291',
                'code' => '764',
                'name' => 'CURRICULUM AND TEACHING',
                'short_name' => 'CURRICULUM AND TEACHING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '292',
                'code' => '766',
                'name' => 'VI:BRAILLE SKILLS',
                'short_name' => 'VI:BRAILLE SKILLS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '293',
                'code' => '767',
                'name' => 'VI:METHODOLOGY',
                'short_name' => 'VI:METHODOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '294',
                'code' => '768',
                'name' => 'VI:VISUAL IMPAIRMENT',
                'short_name' => 'VI:VISUAL IMPAIRMENT',
                'exam_type_id' => '7',
            ],
            [
                'id' => '295',
                'code' => '769',
                'name' => 'VI:ORIENTATION & MOBILITY',
                'short_name' => 'VI:ORIENTATION & MOBILITY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '296',
                'code' => '770',
                'name' => 'HI:HABILITATION & REHABILITA.',
                'short_name' => 'HI:HABILITATION & REHABILITA.',
                'exam_type_id' => '7',
            ],
            [
                'id' => '297',
                'code' => '771',
                'name' => 'HI:AUDIOLOGY',
                'short_name' => 'HI:AUDIOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '298',
                'code' => '772',
                'name' => 'EDUCATION',
                'short_name' => 'EDUCATION',
                'exam_type_id' => '7',
            ],
            [
                'id' => '299',
                'code' => '773',
                'name' => 'HI:HEARING IMPAIRMENT/THE EAR',
                'short_name' => 'HI:HEARING IMPAIRMENT/THE EAR',
                'exam_type_id' => '7',
            ],
            [
                'id' => '300',
                'code' => '774',
                'name' => 'HI:METHODOLOGY',
                'short_name' => 'HI:METHODOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '301',
                'code' => '775',
                'name' => 'II:NEUROLOGY',
                'short_name' => 'II:NEUROLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '302',
                'code' => '776',
                'name' => 'II:S.E.G LEARNING DISABILITIES',
                'short_name' => 'II:S.E.G LEARNING DISABILITIES',
                'exam_type_id' => '7',
            ],
            [
                'id' => '303',
                'code' => '777',
                'name' => 'II:METHODOLOGY',
                'short_name' => 'II:METHODOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '304',
                'code' => '778',
                'name' => 'II:ASSESSMENT HABIL. & REHAB',
                'short_name' => 'II:ASSESSMENT HABIL. & REHAB',
                'exam_type_id' => '7',
            ],
            [
                'id' => '305',
                'code' => '779',
                'name' => 'I.I:SUPPORT SERVICES',
                'short_name' => 'I.I:SUPPORT SERVICES',
                'exam_type_id' => '7',
            ],
            [
                'id' => '306',
                'code' => '781',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENGINEERING SCIENCE',
                'exam_type_id' => '7',
            ],
            [
                'id' => '307',
                'code' => '782',
                'name' => 'ARCHITECTURAL DRAWING',
                'short_name' => 'ARCHITECTURAL DRAWING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '308',
                'code' => '783',
                'name' => 'BUILDING CONSTRUCTION',
                'short_name' => 'BUILDING CONSTRUCTION',
                'exam_type_id' => '7',
            ],
            [
                'id' => '309',
                'code' => '784',
                'name' => 'BRICKWORK & MASONRY',
                'short_name' => 'BRICKWORK & MASONRY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '310',
                'code' => '785',
                'name' => 'WOODWORK',
                'short_name' => 'WOODWORK',
                'exam_type_id' => '7',
            ],
            [
                'id' => '311',
                'code' => '786',
                'name' => 'PAINTING & SIGNWRITING',
                'short_name' => 'PAINTING & SIGNWRITING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '312',
                'code' => '787',
                'name' => 'PLUMBING & PIPEFITTING',
                'short_name' => 'PLUMBING & PIPEFITTING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '313',
                'code' => '788',
                'name' => 'TECHNICAL DRAWING',
                'short_name' => 'TECHNICAL DRAWING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '314',
                'code' => '789',
                'name' => 'METALWORK & MECH PRACT.',
                'short_name' => 'METALWORK & MECH PRACT.',
                'exam_type_id' => '7',
            ],
            [
                'id' => '315',
                'code' => '790',
                'name' => 'AUTOMOBILE TECHNOLOGY',
                'short_name' => 'AUTOMOBILE TECHNOLOGY',
                'exam_type_id' => '7',
            ],
            [
                'id' => '316',
                'code' => '791',
                'name' => 'MACHINE SHOP PRACTICE',
                'short_name' => 'MACHINE SHOP PRACTICE',
                'exam_type_id' => '7',
            ],
            [
                'id' => '317',
                'code' => '792',
                'name' => 'WELDING & FABRICATION',
                'short_name' => 'WELDING & FABRICATION',
                'exam_type_id' => '7',
            ],
            [
                'id' => '318',
                'code' => '793',
                'name' => 'ELECTRONICS',
                'short_name' => 'ELECTRONICS',
                'exam_type_id' => '7',
            ],
            [
                'id' => '319',
                'code' => '794',
                'name' => 'ELECTRICAL INSTALLATION',
                'short_name' => 'ELECTRICAL INSTALLATION',
                'exam_type_id' => '7',
            ],
            [
                'id' => '320',
                'code' => '795',
                'name' => 'ELECTRICAL DRAWING',
                'short_name' => 'ELECTRICAL DRAWING',
                'exam_type_id' => '7',
            ],
            [
                'id' => '321',
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'exam_type_id' => '4',
            ],
            [
                'id' => '322',
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'exam_type_id' => '5',
            ],
            [
                'id' => '323',
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'exam_type_id' => '6',
            ],
            [
                'id' => '324',
                'code' => '0',
                'name' => 'BTP',
                'short_name' => 'BTP',
                'exam_type_id' => '7',
            ],
            [
                'id' => '325',
                'code' => '19',
                'name' => 'THEATRE ART',
                'short_name' => 'THEATRE ART',
                'exam_type_id' => '1',
            ],
            [
                'id' => '326',
                'code' => '11',
                'name' => 'CIVICS',
                'short_name' => 'CIVICS',
                'exam_type_id' => '9',
            ],
            [
                'id' => '327',
                'code' => '12',
                'name' => 'HISTORY',
                'short_name' => 'HISTORY',
                'exam_type_id' => '9',
            ],
            [
                'id' => '328',
                'code' => '13',
                'name' => 'GEOGRAPHY',
                'short_name' => 'GEOGRAPHY',
                'exam_type_id' => '9',
            ],
            [
                'id' => '329',
                'code' => '14',
                'name' => 'BIBLE KNOWLEDGE',
                'short_name' => 'BIBLE KNOWLEDGE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '330',
                'code' => '15',
                'name' => 'ELIMU YA DINI YA KIISLAMU',
                'short_name' => 'ELIMU YA DINI YA KIISLAMU',
                'exam_type_id' => '9',
            ],
            [
                'id' => '331',
                'code' => '16',
                'name' => 'FINE ARTS',
                'short_name' => 'FINE ARTS',
                'exam_type_id' => '9',
            ],
            [
                'id' => '332',
                'code' => '17',
                'name' => 'MUSIC',
                'short_name' => 'MUSIC',
                'exam_type_id' => '9',
            ],
            [
                'id' => '333',
                'code' => '18',
                'name' => 'PHYSICAL EDUCATION',
                'short_name' => 'PHYSICAL EDUCATION',
                'exam_type_id' => '9',
            ],
            [
                'id' => '334',
                'code' => '19',
                'name' => 'THEATRE ARTS',
                'short_name' => 'THEATRE ARTS',
                'exam_type_id' => '9',
            ],
            [
                'id' => '335',
                'code' => '21',
                'name' => 'KISWAHILI',
                'short_name' => 'KISWAHILI',
                'exam_type_id' => '9',
            ],
            [
                'id' => '336',
                'code' => '22',
                'name' => 'ENGLISH LANGUAGE',
                'short_name' => 'ENGLISH LANGUAGE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '337',
                'code' => '23',
                'name' => 'FRENCH LANGUAGE',
                'short_name' => 'FRENCH LANGUAGE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '338',
                'code' => '25',
                'name' => 'ARABIC LANGUAGE',
                'short_name' => 'ARABIC LANGUAGE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '339',
                'code' => '26',
                'name' => 'CHINESE',
                'short_name' => 'CHINESE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '340',
                'code' => '31',
                'name' => 'PHYSICS',
                'short_name' => 'PHYSICS',
                'exam_type_id' => '9',
            ],
            [
                'id' => '341',
                'code' => '32',
                'name' => 'CHEMISTRY',
                'short_name' => 'CHEMISTRY',
                'exam_type_id' => '9',
            ],
            [
                'id' => '342',
                'code' => '33',
                'name' => 'BIOLOGY',
                'short_name' => 'BIOLOGY',
                'exam_type_id' => '9',
            ],
            [
                'id' => '343',
                'code' => '34',
                'name' => 'AGRICULTURE SCIENCE',
                'short_name' => 'AGRICULTURE SCIENCE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '344',
                'code' => '35',
                'name' => 'ENGINEERING SCIENCE',
                'short_name' => 'ENGINEERING SCIENCE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '345',
                'code' => '36',
                'name' => 'INFORMATION & COMPUTER STUDIES',
                'short_name' => 'INFORM. & COMP. STUDIES',
                'exam_type_id' => '9',
            ],
            [
                'id' => '346',
                'code' => '41',
                'name' => 'BASIC MATHEMATICS',
                'short_name' => 'BASIC MATHEMATICS',
                'exam_type_id' => '9',
            ],
            [
                'id' => '347',
                'code' => '42',
                'name' => 'ADDITIONAL MATHEMATICS',
                'short_name' => 'ADDITIONAL MATHEMATICS',
                'exam_type_id' => '9',
            ],
            [
                'id' => '348',
                'code' => '51',
                'name' => 'FOOD & NUTRITION',
                'short_name' => 'FOOD & NUTRITION',
                'exam_type_id' => '9',
            ],
            [
                'id' => '349',
                'code' => '52',
                'name' => 'TEXTILES & DRESSMAKING',
                'short_name' => 'TEXTILES & DRESSMAKING',
                'exam_type_id' => '9',
            ],
            [
                'id' => '350',
                'code' => '61',
                'name' => 'COMMERCE',
                'short_name' => 'COMMERCE',
                'exam_type_id' => '9',
            ],
            [
                'id' => '351',
                'code' => '62',
                'name' => 'BOOK KEEPING',
                'short_name' => 'BOOK KEEPING',
                'exam_type_id' => '9',
            ],
            [
                'id' => '352',
                'code' => '63',
                'name' => 'TYPEWRITING',
                'short_name' => 'TYPEWRITING',
                'exam_type_id' => '9',
            ],
            [
                'id' => '353',
                'code' => '70',
                'name' => 'TECHNICAL DRAWING',
                'short_name' => 'TECHNICAL DRAWING',
                'exam_type_id' => '9',
            ],
            [
                'id' => '354',
                'code' => '71',
                'name' => 'CIVIL ENGINEERING',
                'short_name' => 'CIVIL ENGINEERING',
                'exam_type_id' => '9',
            ],
            [
                'id' => '355',
                'code' => '80',
                'name' => 'ELECTRICAL ENGINEERING',
                'short_name' => 'ELECTRICAL ENGINEERING',
                'exam_type_id' => '9',
            ],
            [
                'id' => '356',
                'code' => '90',
                'name' => 'MECHANICAL ENGINEERING',
                'short_name' => 'MECHANICAL ENGINEERING',
                'exam_type_id' => '9',
            ],
        ];

        $table = $this->table('subjects');
        $table->insert($data)->save();
    }
}
